os: osx
osx_image: xcode9.2
language: c
cache:
  - bundler
  - cocoapods

rvm: 2.3.1

env:
  - PROJECT=Firebase  PLATFORM=iOS   METHOD=xcodebuild
  - PROJECT=Firebase  PLATFORM=macOS METHOD=xcodebuild
  - PROJECT=Firebase  PLATFORM=tvOS  METHOD=xcodebuild
  - PROJECT=Firestore PLATFORM=iOS   METHOD=xcodebuild
  - PROJECT=Firestore PLATFORM=macOS METHOD=cmake

before_install:
  # Add next line back with updated DeviceUDID for xcode9.1 if stability issues with simulator
  # - open -a "simulator" --args -CurrentDeviceUDID ABBD7191-486B-462F-80B4-AE08C5820DA1
  - bundle install
  - gem install xcpretty
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      SKIP_FIREBASE=0
      SKIP_FIRESTORE=0
    else
      git diff --name-only $TRAVIS_COMMIT_RANGE | grep -Eq '^(Firebase|Example)'
      SKIP_FIREBASE="$?"
      git diff --name-only $TRAVIS_COMMIT_RANGE | grep -q Firestore
      SKIP_FIRESTORE="$?"
    fi

jobs:
  include:
    - stage: checks
      # Only enabled on one project/platform combo
      if: env(PROJECT) = Firestore AND env(PLATFORM) = iOS
      before_install:
        - brew install clang-format
        - brew install swiftformat
      script:
        - ./scripts/check_whitespace.sh
        - ./scripts/check_copyright.sh
        - ./scripts/style.sh test-only $TRAVIS_COMMIT_RANGE
        # Google C++ style compliance
        - ./scripts/lint.sh $TRAVIS_COMMIT_RANGE

    - stage: test
      if: env(PROJECT) = Firebase
      language: objective-c
      before_install:
        - |
          if [[ $SKIP_FIREBASE != 1 ]]; then
            bundle exec pod install --project-directory=Example --repo-update
          fi
      script:
        - |
          if [ $SKIP_FIREBASE != 1 ]; then
            ./scripts/build.sh $PROJECT $PLATFORM $METHOD
          fi

        - |
          # TODO fix os_log deprecation warning in FIRLogger to remove --allow-warnings
          if [ $SKIP_FIREBASE != 1 && $PLATFORM == iOS ]; then
            bundle exec pod lib lint FirebaseCore.podspec --allow-warnings
          fi

    - stage: test
      if: env(PROJECT) = Firestore AND env(METHOD) = xcodebuild
      language: objective-c
      before_install:
        - |
          if [[ $SKIP_FIRESTORE != 1 ]]; then
            bundle exec pod install --project-directory=Firestore/Example --repo-update
          fi
      script:
        - |
          if [ $SKIP_FIRESTORE != 1 ]; then
            ./scripts/build.sh $PROJECT $PLATFORM $METHOD
          fi

    - stage: test
      if: env(PROJECT) = Firestore AND env(PLATFORM) = macOS AND env(METHOD) = cmake
      before_install:
        - brew install cmake
        - brew install go # Somehow the build for Abseil requires this.
        - |
          if [[ $SKIP_FIRESTORE != 1 ]]; then
            bundle exec pod install --project-directory=Firestore/Example --repo-update
          fi
      script:
        - |
          if [ $SKIP_FIRESTORE != 1 ]; then
            ./scripts/build.sh $PROJECT $PLATFORM $METHOD
          fi

# TODO - Uncomment subsequent lines once FirebaseCore source repo is in public Specs repo
#  - bundle exec pod lib lint FirebaseAuth.podspec
#  - bundle exec pod lib lint FirebaseDatabase.podspec
#  - bundle exec pod lib lint FirebaseMessaging.podspec --allow-warnings #pending #390 fix
#  - bundle exec pod lib lint FirebaseStorage.podspec
#  - bundle exec pod lib lint Firestore/Firestore.podspec

branches:
  only:
    - master
